sudo: false

language: d

d:
  - dmd
  - ldc

install:
    - sudo apt-get update
    - sudo apt-get install gfortran
    - wget http://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz
    - tar zxvf v0.2.20.tar.gz
    - cd OpenBLAS*
    - travis_wait 30 make FC=gfortran
    - sudo make install
    - cd ../

script: dub --root example

addons:
  apt:
    packages:
      liblapack-dev
