sudo: false

language: d

d:
  - dmd
  - ldc

install:
    - wget http://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz
    - tar zxvf v0.2.20.tar.gz
    - cd OpenBLAS*

script: dub --root example

addons:
  apt:
    packages:
      liblapack-dev
