sudo: false

language: d

d:
  - dmd
  - ldc

install:
    - sudo apt-get update
    - sudo apt-get install gfortran

script:
    - wget http://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz
    - tar zxvf v0.2.20.tar.gz
    - cd OpenBLAS*
    - travis_wait 30 make FC=gfortran
    - sudo make install PREFIX=/home/openblas
    - ls /home/openblas
    - ls /home/openblas/lib
    - cd ../examples/GESVex
    - dub
    - cd ../GEQRSex/source
    - cp /home/openblas/lib/*.so $PWD
    - cp /home/openblas/lib/*.so.0 $PWD
    - cd ../
    - dub

addons:
  apt:
    packages:
      liblapack-dev
