sudo: false

language: d

d:
  - dmd
  - ldc

install:
    - sudo apt-get update
    - sudo apt-get install gfortran

script:
    - wget http://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz
    - tar zxvf v0.2.20.tar.gz
    - cd OpenBLAS*
    - travis_wait 30 make FC=gfortran
    - sudo make install PREFIX=/home/openblas
    - export PATH = "/home/openblas/bin:$PATH"
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/openblas/lib:$HOME/lib:$/usr/local/lib
    - export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/lib:/home/openblas/lib
    - echo $LD_LIBRARY_PATH
    - echo $PATH
    - cd ../examples/GESVex
    - dub
    - cd ../GEQRSex/source
    - cp /home/openblas/lib/*.so $PWD
    - cp /home/openblas/lib/*.so.0 $PWD
    - cd ../
    - cp /home/openblas/lib/*.so $PWD
    - cp /home/openblas/lib/*.so.0 $PWD
    - dub

addons:
  apt:
    packages:
      liblapack-dev
