sudo: false

language: d

d:
  - dmd
  - ldc

install:
    - travis_wait 30 mvn install
    - wget http://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz
    - tar zxvf v0.2.20.tar.gz
    - cd OpenBLAS*
    - make FC=gfortran
    - sudo make install

script: dub --root example

addons:
  apt:
    packages:
      liblapack-dev
